### ISSUE TITLE
Crash to desktop with version 2023.03.28.3

### ISSUE THREAD

**Issue by kretze** [TweakScale/Companion#25]
if i have installed version 2023.03.28.3, it ends in a crash to desktop when starting KSP.

is it normal that in many places in paths without gameplay folders are searched for?
*** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScale
[TweakScale] ERROR: Could not check the presense of TweakScale Companion due Could not find file "E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScaleCompanion" at error:0

Log with 2023.03.28.3
```
[LOG 19:43:53.625] [TweakScale] Version 2.4.7.1 /L
[LOG 19:43:53.647] *** TweakScale
[LOG 19:43:53.647] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScale
[LOG 19:43:53.647] *** TweakScale || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[ERR 19:43:53.656] ADDON BINDER: Cannot resolve assembly: Scale.PartDB.19x

[LOG 19:43:53.657] [KSPe.Binder] Looking for Scale.PartDB.19x.dll on GameData\TweakScale\Plugins\PluginData\...
[LOG 19:43:53.658] [KSPe.Binder] Found it on E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\GameData\TweakScale\Plugins\PluginData\Scale.PartDB.19x.dll.
[LOG 19:43:53.661] [TweakScale] Support for KSP 1.9.0 to 1.12.5 Version 2.4.7.1 /L
[LOG 19:43:53.793] *** TweakScale
[LOG 19:43:53.793] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScale
[LOG 19:43:53.793] *** TweakScale || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[LOG 19:43:53.798] [TweakScale] ERROR: Could not check the presense of TweakScale Companion due Could not find file "E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScaleCompanion" at error:0
[LOG 19:43:53.864] [TweakScaleCompanion.Frameworks] Version 0.4.0.2 /L BETA
[LOG 19:43:53.903] *** TweakScaleCompanion\Frameworks
[LOG 19:43:53.903] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScaleCompanion\Frameworks
[LOG 19:43:53.903] *** TweakScaleCompanion\Frameworks || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[LOG 19:43:53.907] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
[LOG 19:43:53.941] *** TweakScaleCompanion\Frameworks\TestFlightCore
[LOG 19:43:53.942] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScaleCompanion\Frameworks\TestFlightCore
[LOG 19:43:53.942] *** TweakScaleCompanion\Frameworks\TestFlightCore || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[LOG 19:43:53.951] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
[LOG 19:43:53.952] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
[LOG 19:43:53.953] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
...
...
[LOG 19:43:54.491] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
[LOG 19:43:54.493] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
[LOG 19:43:54.494] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
[LOG 19:43:54.495] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.2 /L BETA is loaded.
End of file
```
-> Crash to Desktop

if I take the TweakScalerTestFlightCore.dll from version  2023.03.28.2 the game starts again
then there is a DllNotFoundException: error, but KSP is starting

###############################################################

logs with 2023.03.28.2 dll - TweakScalerTestFlightCore.dll

```
[LOG 19:49:28.106] [TweakScale] Version 2.4.7.1 /L
[LOG 19:49:28.126] *** TweakScale
[LOG 19:49:28.126] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScale
[LOG 19:49:28.126] *** TweakScale || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[ERR 19:49:28.135] ADDON BINDER: Cannot resolve assembly: Scale.PartDB.19x

[LOG 19:49:28.136] [KSPe.Binder] Looking for Scale.PartDB.19x.dll on GameData\TweakScale\Plugins\PluginData\...
[LOG 19:49:28.137] [KSPe.Binder] Found it on E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\GameData\TweakScale\Plugins\PluginData\Scale.PartDB.19x.dll.
[LOG 19:49:28.139] [TweakScale] Support for KSP 1.9.0 to 1.12.5 Version 2.4.7.1 /L
[LOG 19:49:28.216] *** TweakScale
[LOG 19:49:28.216] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScale
[LOG 19:49:28.216] *** TweakScale || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[LOG 19:49:28.222] [TweakScale] ERROR: Could not check the presense of TweakScale Companion due Could not find file "E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScaleCompanion" at error:0
[LOG 19:49:28.289] [TweakScaleCompanion.Frameworks] Version 0.4.0.2 /L BETA
[LOG 19:49:28.327] *** TweakScaleCompanion\Frameworks
[LOG 19:49:28.327] *** E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\TweakScaleCompanion\Frameworks
[LOG 19:49:28.327] *** TweakScaleCompanion\Frameworks || E:\SteamLibrary1\steamapps\common\Kerbal Space Program 1.12.3 RP-1 2023\
[LOG 19:49:28.331] [TweakScaleCompanion.Frameworks] TweakScalerTestFlightCore Version 0.4.0.1 /L BETA is loaded.
[EXC 19:49:28.378] DllNotFoundException: An Add'On Support DLL was not loaded. Missing type : TweakScaleCompanion.Frameworks.TestFlightCore.Version
	KSPe.Util.SystemTools+Type+Find.ByQualifiedName (System.String qn) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.Util.SystemTools+Type+Find.By (System.String ns, System.String name) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.Util.SystemTools+Reflection+Version`1[T]..cctor () (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	Rethrow as TypeInitializationException: The type initializer for 'Version`1' threw an exception.
	KSPe.IO.Hierarchy`1[T].calculateTypeRoot () (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.IO.Hierarchy`1[T].CalculateTypeRoot () (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.IO.Hierarchy`1[T]..ctor (KSPe.IO.Hierarchy hierarchy) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.IO.Hierarchy`1[T]..cctor () (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	Rethrow as TypeInitializationException: The type initializer for 'KSPe.IO.Hierarchy`1' threw an exception.
	KSPe.Util.SystemTools+Assembly+Loader`1[T].TryPath (System.String path, System.String[] subdirs) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.Util.SystemTools+Assembly+Loader.buildSearchPath (System.String[] subdirs) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.Util.SystemTools+Assembly+Loader..ctor (System.String[] subdirs) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	KSPe.Util.SystemTools+Assembly+Loader`1[T]..ctor (System.String[] subdirs) (at <58fb44557e3d487fa13c42bddbc423e1>:0)
	TweakScaleCompanion.Frameworks.TestFlightCore.Startup.loadDLLs () (at <167c16a47da54d53885d62c6afddd8a8>:0)
	TweakScaleCompanion.Frameworks.TestFlightCore.Startup.Start () (at <167c16a47da54d53885d62c6afddd8a8>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 19:49:28.379] [Waterfall][Asset Library]: Started loading
[LOG 19:49:28.379] [Waterfall][Asset Library]: Loading models
[LOG 19:49:28.385] [Waterfall][Asset Library]: Loaded 12 models
[LOG 19:49:28.385] [Waterfall][Asset Library]: Loading textures
[LOG 19:49:28.390] [Waterfall][Asset Library]: Loaded 27 textures
[LOG 19:49:28.390] [Waterfall][Asset Library]: Loading shaders
[LOG 19:49:28.395] [Waterfall][Asset Library]: Loaded 11 shaders
[LOG 19:49:28.395] [Waterfall][Asset Library]: Finished loading
[LOG 19:49:28.395] [TweakScaleCompanion.FS] Version 1.3.0.0 /L
[LOG 19:49:28.400] [TweakScaleCompanion.KIAS] Version 1.1.0.0 /L
[LOG 19:49:28.410] [TweakScaleCompanion.PKMC] Version 2.2.1.1 /L
[LOG 19:49:28.480] *** TweakScaleCompanion\PKMC
```

**Comment by Lisias** [comment]
Hi, @kretze !

Thanks for the report. You found something wrong on the TSCO_Frameworks related to the TestFlightCore - the thing is being load and loaded again until the bitter crash!

I will investigate the problem ASAP, I don't have the slightest idea about what's happening because, well, this crap didn't happened on my test beds.

Can you please send me your full KSP.log and Player.log where the problem happens?

**Comment by Lisias** [comment]
In the mean time, bluntly remove `TweakScaleCompanion\Frameworks\TestFlightCore` from your `GameData`. It's safer to fully remove the whole feature that letting leftovers lingering around risking screwing up the `Assembly Loader/Resolver`

**Comment by kretze** [comment]
[Tweakscale_Companion_2023.03.28.3-#25.zip](https://github.com/TweakScale/Companion/files/11408709/Tweakscale_Companion_2023.03.28.3-.25.zip)

KSP + player logs

**Comment by Lisias** [comment]
Oukey, so I created a near naked KSP 1.12.3 installation with 

* Latest [KSPe](https://github.com/net-lisias-ksp/KSPe/releases/tag/RELEASE%2F2.5.2.0)
* Latest [MM/L](https://github.com/net-lisias-ksp/ModuleManager/releases/tag/RELEASE%2F4.2.2.5)
* Latest [KSP-Recall](https://github.com/net-lisias-ksp/KSP-Recall/releases/tag/RELEASE%2F0.4.0.1)
* Latest [MMWD](https://github.com/net-lisias-ksp/ModuleManagerWatchDog/releases/tag/RELEASE%2F1.1.0.4)
* Latest [TweakScale](https://github.com/TweakScale/TweakScale/releases/tag/RELEASE%2F2.4.7.1)
* Latest [TweakScaleCompanion Uberpaket](https://github.com/TweakScale/Companion/releases/tag/RELEASE%2F2023.03.28.3).
* Latest [TestFlight](https://github.com/KSP-RO/TestFlight/releases/tag/v2.5.0.0)
* Latest [Stock+-TF-Configs](https://github.com/Starstrider42/TestFlight-Configs/releases/tag/0.2.0)

And fired the thing up to see what happens and… yeah, I reproduced the problem without effort.

We can nail the (currently) probable suspects to:

* KSPe (and its DLL loading subsystem, that the Companions rely on)
* The `TweakScaleCompanion/Frameworks/TestFlightCore` itself, perhaps with some stupid bug while handling the DLL helper
* Something pretty weird with TestFlight 2.5 itself (I don't remember testing this thing with this specific version).

In a way or another, this test session rule out any other Add'On installed on the user's machine, as I could reproduce the problem using the subset listed above.

@kretze , keep `TweakScaleCompanion\Frameworks\TestFlightCore` away from your rig until further notice.

**Comment by Lisias** [comment]
This piece of *krap* I published is not the same *krap* I tested.

I must had make some really, really stupid mistake after testing it and before publishing it.

In a nutshell: I screwed up on the code, and somehow I used an interim version of KSPe while validating the DLL where the borkage was being worked around. Once he thing hit the shelves, it had to cope with the KSPe.Light already on the streets, that doesn't have the feature.

Well… Time to code some mitigating measures.

**Comment by kretze** [comment]
1.12.3 is the current version for RP-1. I had updated my rp-1 installation to 1.12.5 in march and then had problems with the KSP ending in a crash to desktop (can't remember what the cause was. I still have the ksp.log from 03/18/23). then i put together a fresh 1.12.3 version with rp-1.

as long as RP-1 still relies on 1.12.3, this version should probably also be tested.

I have removed TestFlightCore and will remove it as long as the bug is not fixed.

**Comment by Lisias** [comment]
> I will test the days if the current installation (with the used mods) is now running in 1.12.5.

I'm almost sure it will. I was the one borking on this. :) In a pretty interesting and convoluted way… :P
